config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
=======
  resources :property_images
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
<<<<<<< HEAD
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
=======
    :omniauth_callbacks => "omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  get "/popups/signup" => "popup#signup"
  get "/popups/login" => "popup#login"
  get "/popups/password" => "popup#password"

<<<<<<< HEAD
   get "/subscriptions/subscribe" => "subscriptions#subscribe"

=======
  get "/subscriptions/subscribe" => "subscriptions#subscribe"

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :registrations
  resources :plans do
    collection do
      get :payments
    end
  end

  resources :p_listings do
    resources :property_images
  end

<<<<<<< HEAD
  resources :pdetails
  resources :cdns
=======
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :home
  resources :searches
  resources :property_images

  root 'home#index'

end

app/models/p_listing.rb
class PListing < ActiveRecord::Base

	has_many :property_images
	accepts_nested_attributes_for :property_images

	# before_save :do_something

	# def do_something
	# 	self.total_time = self.time_out - self.time_in
	# end

geocoded_by :street
after_validation :geocode



        def self.search(search)
    	if search
    	where(["street ILIKE ? OR city_place ILIKE ?","%#{search}%", "%#{search}%"])
    	else
    	all 
    	end
    end



end

app/controllers/p_listings_controller.rb
class PListingsController < ApplicationController
  before_action :set_p_listing, only: [:show, :edit, :update, :destroy]

  # GET /p_listings
  # GET /p_listings.json
  def index

    @property_images = PListing.__id__

    @p_listings = PListing.search(params[:search])
    @search = Search.new
    @ptypes = PListing.uniq.pluck(:property_type)
    @rooms = PListing.uniq.pluck(:room)
    @bathroom = PListing.uniq.pluck(:bathroom)
    @rent_price = PListing.uniq.pluck(:total_rent)
  
 
  @hash = Gmaps4rails.build_markers(@p_listings) do |plisting, marker|
  marker.lat plisting.latitude
  marker.lng plisting.longitude
  marker.infowindow plisting.street

       #  marker.picture({
       # "url" => "marker-logo.png",
       # "width" =>  32,
       # "height" => 32})

  marker.json({title: plisting.title})


end

  end
  
def show
  @property_images = @p_listing.property_images.all
  # @p_listings_parameters = PListing.find(params[:id]).parameters
  # @p_listing = PListing.find params[:id]
  
  @hash = Gmaps4rails.build_markers(@p_listing) do |plisting, marker|
    marker.lat plisting.latitude
    marker.lng plisting.longitude
    marker.infowindow plisting.street
    #marker.json({title: plisting.title})
  end
end
  # GET /p_listings/1
  # GET /p_listings/1.json


  # GET /p_listings/new
  def new
    @p_listing = PListing.new
    @property_image = @p_listing.property_images.build
    @search = Search.new
  end

  # GET /p_listings/1/edit
  def edit
    @property_image = @p_listing.property_images.build
  end

  # POST /p_listings
  # POST /p_listings.json
  def create
    @p_listing = PListing.new(p_listing_params)
    respond_to do |format|
      if @p_listing.save
        params[:property_images]['image_file'].each do |a|
          @property_image = @p_listing.property_images.create!(:image_file => a)
        end
        format.html { redirect_to @p_listing, notice: 'P listing was successfully created.' }
        format.json { render :show, status: :created, location: @p_listing }
      else
        format.html { render :new }
        format.json { render json: @p_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /p_listings/1
  # PATCH/PUT /p_listings/1.json
  def update
    respond_to do |format|
      if @p_listing.update(p_listing_params)
        format.html { redirect_to @p_listing, notice: 'P listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @p_listing }
      else
        format.html { render :edit }
        format.json { render json: @p_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /p_listings/1
  # DELETE /p_listings/1.json
  def destroy
    @p_listing.destroy
    respond_to do |format|
      format.html { redirect_to p_listings_url, notice: 'P listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_p_listing
      @p_listing = PListing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def p_listing_params
      params.require(:p_listing).permit(:display_type, :use_type, :property_type, :title, :street, :house_no, :city_place, :zip_code, :flat_size, :room, :bathroom, :total_rent, :date, :description, :longitude, :latitude , property_images_attributes: [:id, :p_listing_id, :image_file])
    end
end

app/helpers/p_listings_helper.rb
module PListingsHelper
end

app/views/p_listings/_form.html.erb
<%= form_for(@p_listing, :html => { :multipart => true }) do |f| %>
  <% if @p_listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@p_listing.errors.count, "error") %> prohibited this p_listing from being saved:</h2>

      <ul>
      <% @p_listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

<br><br>
    <div class="col-lg-7 col-md-10 col-sm-10 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title"><h4>Property Advertisement</h4></div>
        </div>
        <div class="panel-body">

  <div class="col-md-11 col-sm-12 col-xs-12 col-md-offset-2">
<br><br>

    <div class="col-md-9 col-sm-9 col-xs-10">
<div class="row">

  
  <div class="radio-inputs test-font">
    <div class="radio-inputs-lable"><span class="radio-label-span">Display Type</span></div>
    
    <div style="margin-left:150px; line-height:2.5;">


      <label class="rad">
      <%= f.text_field :display_type, type:"radio", value:"Rent", class:"checkradios" %>
      <i></i></label>&nbsp;Rent&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      
      <label class="rad">
      <%= f.text_field :display_type, type:"radio", value:"Purchase" %><i></i></label>&nbsp;Purchase
  
    </div>

  </div>

</div>
</div><br><br>


<div class="col-md-9 col-sm-9 col-xs-10">
  <div class="row">
  <div class="radio-inputs test-font">
    <div class="radio-inputs-lable"><span class="radio-label-span">Type of Use</span></div>

  <div style="margin-left:150px; line-height:2.5;">

      <label class="rad">
      <%= f.text_field :use_type, type:"radio", value:"Living" %><i></i></label>&nbsp;Living&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <label class="rad">
      <%= f.text_field :use_type, type:"radio", value:"Trade" %><i></i></label>&nbsp;Trade
  
  </div>
  </div>

</div>
</div><br><br>

    <div class="col-md-9 col-sm-9 col-xs-10">
    <div class="row">
  
  <div class="radio-inputs test-font">
    <div class="radio-inputs-lable"><span class="radio-label-span">Property Type</span></div>
        <div style="margin-left:150px; line-height:2.5;">
  
      <label class="rad">
      <%= f.text_field :property_type, type:"radio", value:"Apartment" %><i></i></label>&nbsp;Apartment&nbsp;&nbsp;
      <label class="rad">
      <%= f.text_field :property_type, type:"radio", value:"House" %><i></i></label>&nbsp;House&nbsp;&nbsp;
      <label class="rad">
      <%= f.text_field :property_type, type:"radio", value:"Property" %><i></i></label>&nbsp;Property

    </div>
  </div>

</div>
</div><br><br><br>


    <div class="col-md-9 col-sm-9 col-xs-10">
      <div class="row">
      <%= f.text_field :title, class:"form-control", id:"p_listing_title", placeholder:"Title of the Display" %>
</div>
</div><br><br>


<div class="col-sm-6 col-xs-6 padding_colsm6">
  <div class="row">
  <%= f.text_field :street, class:"form-control", id:"p_listing_street", placeholder:"View Street" %>
</div>
  </div>
<div class="col-sm-3 col-xs-4 padding_colsm3">
  <div class="row">
  <%= f.text_field :house_no, class:"form-control", id:"p_listing_house_no", placeholder:"House No." %>

</div>
</div><br><br>

<div class="col-sm-6 col-xs-6 padding_colsm6">
  <div class="row">
  <%= f.text_field :city_place, class:"form-control", id:"p_listing_city_place", placeholder:"Place" %>
</div>
  </div>
<div class="col-sm-3 col-xs-4 padding_colsm3">
  <div class="row">
  <%= f.text_field :zip_code, class:"form-control", id:"p_listing_zip_code", placeholder:"Zip Code" %>
</div>
</div>
<br><br>

<div class="col-sm-6 col-xs-6 padding_colsm6">
  <div class="row">
  <%= f.text_field :flat_size, class:"form-control", id:"p_listing_flat_size", placeholder:"Rasidential Area                                       m2" %>
</div>
  </div>
<div class="col-sm-3 col-xs-4 padding_colsm3">
  <div class="row">
  <%= f.text_field :room, class:"form-control", id:"p_listing_room", placeholder:"Room" %>
</div>
</div>
<br><br>

<div class="col-sm-6 col-xs-6 padding_colsm6">
  <div class="row">
  <%= f.text_field :total_rent, class:"form-control", id:"p_listing_total_rent", placeholder:"Total Rent(warm)" %>
</div>
</div>
  <div class="col-sm-3 col-xs-4 padding_colsm3">
  <div class="row">
  <%= f.text_field :bathroom, class:"form-control", id:"p_listing_bathroom", placeholder:"Bathroom" %>
</div>
</div>
<br><br>

<div class="col-sm-6 col-xs-6 padding_colsm6">
  <div class="row">
<div class="calender-icon">
<span><i class="fa fa-calendar fa-lg"></i></span> 
     <%= f.text_field :date, id:"datepicker",:autocomplete => :off,  :placeholder => "Available From", class:"form-control" %>
</div>


</div>
</div><br><br>

    <div class="col-md-9 col-sm-9 col-xs-10">
      <div class="row">
        <%= f.text_area :description, class:"form-control", id:"p_listing_description", placeholder:"Property Description (Max. 2000 Words)", style:"height:200px; width:100%;" %>
        </div>
    </div><br><br><br><br><br><br><br><br><br><br><br>

    <div class="col-md-9 col-sm-9 col-xs-10">
<div class="row">
  <%= f.fields_for :property_images do |p| %>
      <% if p.object.new_record? %>
<div class="upload-box">
   <div class="upload-entypo">
        
<span id="target"><h2 style="text-align:center; margin-top:52px;"><i class="fa fa-camera"></i></h2></span>
    
    </div>
    <p class="test-font" style="margin-top: 22px;"><strong>Add Photos</strong><br> Drag a Photo from a folder over here or click here to </p>

      <div class="fileUpload btn-upload">

<span class="test-font">Upload</span>

<%= p.file_field :image_file, type: :file, :multiple => true, name:"property_images[image_file][]", class:"upload", id:"p_listing_p_image" %>


</div>

      </div>
<p class="test-font" style="float: left;"><mark class="note">Note:</mark>
Allowed Formates for photos are .JPG, .PNG, .GIF, Maximum Size of one photo is 5MB.</p>
      <% else %>

          <div class="images-box">

                <a href="/p_listings/<%= @p_listing.id %>/property_images/<%= p.object.id %>" data-method="delete" onclick="return confirm('Are you sure ?')">
                <%= image_tag(p.object.image_file.url) rescue '' %>
                  <acronym title="Remove image"><span><i class="fa fa-times-circle fa-3x" aria-hidden="true"></i></span></acronym>
                </a>

          </div>
      <% end %>
  <% end %>
</div>
</div>

  <div class="field">
    
    <%= f.text_field :longitude, type:"hidden" %>
  </div>
  <div class="field">
    
    <%= f.text_field :latitude, type:"hidden" %>
  </div>

<div class="col-md-9 col-sm-9 col-xs-10">
  <div class="row form-btn-row">
<%= link_to 'Back', p_listings_path, class: "btn btn-back btn-lg" %>

<%= f.submit "Continue", class: "btn btn-save btn-lg" %>

</div>
</div>

</div>
</div>
</div>
</div>


<% end %>

app/views/p_listings/edit.html.erb
<%= render 'form' %>

app/views/p_listings/index.html.erb
<br><br>
<div class="container-fluid">

<div class="col-md-7 col-sm-10 col-xs-12" style="width: 58.333333%;">
<div class="row">

<%= form_for @search, html: {class: "form-inline"} do |s| %>


  <div class="form-group">
    <%= s.select :p_type, options_for_select(@ptypes), {include_blank: "Property Type"}, { class:"ptype_dropdown" }  %>
  
  </div>

  <div class="form-group">
    <%= s.select :bedroom, options_for_select(@rooms), {include_blank: "Bedroom"}, { class:"pbedroom_dropdown" } %>
  </div>

  <div class="form-group">
    <%= s.select :bathroom, options_for_select(@bathroom), {include_blank: "Bathroom"}, { class:"pbathroom_dropdown" } %>
  </div>

  <div class="form-group">
    <%= s.select :rent, options_for_select(@rent_price), {include_blank: "$  Max "}, { class:"prent_dropdown" } %>
  </div>

  <div class="form-group"><%= s.submit "Detailed Search", class: "btn-Dsearch" %></div>

 <% end %>  

</div>


<br>

<div class="row">

<% @p_listings.each do |p_listing| %>

    <div class="thumbnail">
      <%= image_tag p_listing.property_images.first.try(:image_file).try(:url), :class => "style_image" %>
      <div class="rent-on-img">$ <%= p_listing.total_rent %></div>
      <div class="image-footer">
        <div class="footer-text">City <%= p_listing.city_place %> - <%= p_listing.property_type %> at <%= p_listing.street %><br>
         Bathroom - <%= p_listing.bathroom %> | Bed - <%= p_listing.room %>
       
        <%= link_to 'View', p_listing %>
        <%= link_to 'Edit', edit_p_listing_path(p_listing) %>
        <%= link_to 'Delete', p_listing, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>

      </div>

    </div>

  <% end %>

 </div>

 <div class="row">
<nav>
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

<%= link_to 'Add New', new_p_listing_path, class: 'btn btn-default' %>
</div>

<br><br>

</div>


<div class="hidden-xs hidden-sm">

<div class="row">

  <div class="index-map-div" id="map">

  </div>
  
</div>
</div>
 
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

</div>

app/views/p_listings/new.html.erb
<!-- <h1>New P Listing</h1> -->

<%= render 'form' %>

app/views/p_listings/show.html.erb
   <br><br>
<p id="notice"><%= notice %></p>

<div class="container-fluid">


    <div class="col-md-7 col-sm-10 col-xs-12">
      <div class="row">
      <div class="panel panel-default">

        <div class="listing-heading">
          <div class="panel-title">
            <h4>City <%= @p_listing.city_place %>-<%= @p_listing.street %><span style="float:right">$ <%= @p_listing.total_rent %></span></h4>
            <h5>Property for <%= @p_listing.display_type %> | House No. <%= @p_listing.house_no %></td></h5>
          </div>
        </div>
        <div class="panel-body">
          <div class="slider-div">

            <ul class="bxslider">

              <% @property_images.each do |i| %>

                  <li><%= image_tag i.image_file.url, :style => "width:100%; height:320px;" %></li>

              <%end%>
            </ul>

            <div id="bx-pager">
              <% @property_images.each do |i| %>
              <%= image_tag i.image_file.url(:thumb) %>
              <%end%>
            </div>

            </div>

          <div class="panel panel-default">
            <div class="description-panel"><h4>Description</h4></div>
            <div class="panel-body">
              <%= @p_listing.description %>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="description-panel"><h4>Key Facts</h4></div>
            <div class="panel-body">

              Area <%= @p_listing.flat_size %> | Room <%= @p_listing.room %> | Rent <%= @p_listing.total_rent %>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="description-panel"><h4>Equipment</h4></div>
            <div class="panel-body">
              <%= @p_listing.description %>
            </div>
          </div>


<%= link_to 'Edit', edit_p_listing_path(@p_listing), class: 'btn btn-default' %> |
<%= link_to 'Back', p_listings_path, class: 'btn btn-default' %>

</div>
</div>
</div>



</div>

  <div class="hidden-xs hidden-sm">
  <div class="col-md-5 map-div-margin">
    <div class="row">
    <div class="panel panel-default">
      <div class="map-panel-heading"><h4>Location Information</h4>
      <span  style="float: right;margin-top: -29px;"><li class="fa fa-bars fa-lg"></li></span>
      </div>
      <div class="panel-body map-div" id="map">

</div>
      </div>
</div>

    <div class="row">
      <div class="panel panel-default">
        <div class="contact-panel-heading"><h4>Contact Provider</h4>
          <span  style="float: right;margin-top: -29px;"><li class="fa fa-envelope fa-lg"></li></span>
        </div>
        <div class="panel-body">
          <%= link_to 'Contact', p_listings_path, class:'btn btn-contact' %>

        </div>
      </div>
    </div>
    </div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
</script>

</div>