config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
=======
  resources :property_images
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
<<<<<<< HEAD
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
=======
    :omniauth_callbacks => "omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  get "/popups/signup" => "popup#signup"
  get "/popups/login" => "popup#login"
  get "/popups/password" => "popup#password"

<<<<<<< HEAD
   get "/subscriptions/subscribe" => "subscriptions#subscribe"

=======
  get "/subscriptions/subscribe" => "subscriptions#subscribe"

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :registrations
  resources :plans do
    collection do
      get :payments
    end
  end

  resources :p_listings do
    resources :property_images
  end

<<<<<<< HEAD
  resources :pdetails
  resources :cdns
=======
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :home
  resources :searches
  resources :property_images

  root 'home#index'

end

app/views/partials/_footer.html.erb
<footer>


<div class="col-md-12 col-sm-12 col-xs-12">
<div class="footer">
<h4 class="left txt-color">Copyrights - Wallchalking Ltd.</h4>

<h4 class="right">
<a href="#">About Us</a>&nbsp;&nbsp;
<a href="#">Contact</a>&nbsp;&nbsp; 
<a href="#">Contact Us</a>&nbsp;&nbsp;
<!-- <a href="#">impressum</a>&nbsp;&nbsp; -->
<a href="#">impressum</a>&nbsp;&nbsp;&nbsp;&nbsp;

<a href="#" title="" class="btn btn-icon-btn"><i class="fa fa-facebook fbk"></i></a>
<a href="#" title="" class="btn btn-icon-btn"><i class="fa fa-twitter twt"></i></a>
<a href="#" title="" class="btn btn-icon-btn"><i class="fa fa-instagram inst"></i></a>
</h4>	
</div>
</div>


</footer>

app/views/partials/_signup.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/partials/_topbar.html.erb
   <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"></span>
        <!-- <i class="fa fa-bars fa-lg"></i> -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <% if params[:controller] == 'home' %>

   <a href="/home" title="" class="navbar-brand btn logo"><%= image_tag("logo.png", class:"logo-image") %></a>
   
    <% else %>
  
  <a href="/home" title="" class="navbar-brand btn logo"><%= image_tag("logo_transparent.png", class:"single_logo") %></a>

   <%= form_tag p_listings_path, :method => 'get' do  %>
  <div class="row">
  <div class="col-xs-4 col-sm-5 hidden-sm hidden-xs">
  <div class="logo-right-search-icon">
  <span><h3><i class="fa fa-search fa-sm"></i></h3></span>
  <%= text_field_tag :search, params[:search], class:"form-control logo-search-input", placeholder: "What are you looking for ?" %>
  </div>
  </div>
  </div>
  <% end %>
    <% end %>



</div>
<div class="col-md-12 col-sm-12 col-xs-12 collapse navbar-collapse right" id="bs-example-navbar-collapse-1">

<% if user_signed_in? %>

<%= link_to "Sign Out", destroy_user_session_path, method: :delete , class: "btn btn_signout" %>
<% else %>
<%= link_to "Sign In", '/popups/login', remote: "true", class: "btn btn_signin" %>
<% end %>

<%= link_to "Post Property", new_p_listing_path, class:"btn btn_post_property"  %>




</div>