config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
=======
  resources :property_images
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
<<<<<<< HEAD
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
=======
    :omniauth_callbacks => "omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  get "/popups/signup" => "popup#signup"
  get "/popups/login" => "popup#login"
  get "/popups/password" => "popup#password"

<<<<<<< HEAD
   get "/subscriptions/subscribe" => "subscriptions#subscribe"

=======
  get "/subscriptions/subscribe" => "subscriptions#subscribe"

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :registrations
  resources :plans do
    collection do
      get :payments
    end
  end

  resources :p_listings do
    resources :property_images
  end

<<<<<<< HEAD
  resources :pdetails
  resources :cdns
=======
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :home
  resources :searches
  resources :property_images

  root 'home#index'

end

app/models/property_image.rb
class PropertyImage < ActiveRecord::Base

  mount_uploader :image_file, ImageUploader
  belongs_to :p_listing

  has_attached_file :image_file, :styles => { :medium => "300x300>",
                                              :slides => "300x100>",
                                              :thumb => "100x100>",
                                              :small => "150x150>" }

  validates_attachment 	:image_file,
                        :presence => true,
                        :content_type => { :content_type => /\Aimage\/.*\Z/ },
                        :size => { :less_than => 1.megabyte }

end

app/controllers/property_images_controller.rb
class PropertyImagesController < ApplicationController
  before_action :set_property_image, only: [:show, :edit, :update, :destroy]

  # GET /property_images
  # GET /property_images.json
  def index
    @property_images = PropertyImage.all
  end

  # GET /property_images/1
  # GET /property_images/1.json
  def show
  end

  # GET /property_images/new
  def new
    @property_image = PropertyImage.new
  end

  # GET /property_images/1/edit
  def edit
  end

  # POST /property_images
  # POST /property_images.json
  def create
    @property_image = PropertyImage.new(property_image_params)

    respond_to do |format|
      if @property_image.save
        format.html { redirect_to @property_image, notice: 'Property image was successfully created.' }
        format.json { render :show, status: :created, location: @property_image }
      else
        format.html { render :new }
        format.json { render json: @property_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_images/1
  # PATCH/PUT /property_images/1.json
  def update
    respond_to do |format|
      if @property_image.update(property_image_params)
        format.html { redirect_to @property_image, notice: 'Property image was successfully updated.' }
        format.json { render :show, status: :ok, location: @property_image }
      else
        format.html { render :edit }
        format.json { render json: @property_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_images/1
  # DELETE /property_images/1.json
  def destroy
    @p_listing = PListing.find params[:p_listing_id]
    @property_image = PropertyImage.find(params[:id])
    @property_image.destroy
    respond_to do |format|
      format.html { redirect_to edit_p_listing_path(@p_listing), notice: 'Property image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property_image
      @property_image = PropertyImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_image_params
      params.require(:property_image).permit(:p_listing_id, :image_file)
    end
end

app/helpers/property_images_helper.rb
module PropertyImagesHelper
end

app/views/property_images/_form.html.erb
<%= form_for(@property_image) do |f| %>
  <% if @property_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property_image.errors.count, "error") %> prohibited this property_image from being saved:</h2>

      <ul>
      <% @property_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :p_listing_id %><br>
    <%= f.number_field :p_listing_id %>
  </div>
  <div class="field">
    <%= f.label :image_file %><br>
    <%= f.text_field :image_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/property_images/edit.html.erb
<h1>Editing Property Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @property_image %> |
<%= link_to 'Back', property_images_path %>

app/views/property_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Property Images</h1>

<table>
  <thead>
    <tr>
      <th>P listing</th>
      <th>Image file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @property_images.each do |property_image| %>
      <tr>
        <td><%= property_image.p_listing_id %></td>
        <td><%= property_image.image_file %></td>
        <td><%= link_to 'Show', property_image %></td>
        <td><%= link_to 'Edit', edit_property_image_path(property_image) %></td>
        <td><%= link_to 'Destroy', property_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property image', new_property_image_path %>

app/views/property_images/new.html.erb
<h1>New Property Image</h1>

<%= render 'form' %>

<%= link_to 'Back', property_images_path %>

app/views/property_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>P listing:</strong>
  <%= @property_image.p_listing_id %>
</p>

<p>
  <strong>Image file:</strong>
  <%= @property_image.image_file %>
</p>

<%= link_to 'Edit', edit_property_image_path(@property_image) %> |
<%= link_to 'Back', property_images_path %>