config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
=======
  resources :property_images
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
<<<<<<< HEAD
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
=======
    :omniauth_callbacks => "omniauth_callbacks"
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  get "/popups/signup" => "popup#signup"
  get "/popups/login" => "popup#login"
  get "/popups/password" => "popup#password"

<<<<<<< HEAD
   get "/subscriptions/subscribe" => "subscriptions#subscribe"

=======
  get "/subscriptions/subscribe" => "subscriptions#subscribe"

>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :registrations
  resources :plans do
    collection do
      get :payments
    end
  end

  resources :p_listings do
    resources :property_images
  end

<<<<<<< HEAD
  resources :pdetails
  resources :cdns
=======
>>>>>>> 88bfef548e4799da95d94ecde8a300b2fe52d038
  resources :home
  resources :searches
  resources :property_images

  root 'home#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_one :registration

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  #before_action :set_plan, only: [:show, :edit, :update, :destroy]
  #layout "application"

  # GET /courses

def show

end

    def payments
      @plan1 = Plan.find(1)
      @plan2 = Plan.find(2)
      @plan3 = Plan.find(3)
      @plan4 = Plan.find(4)
    end
=begin

  def set_plan
    @plan = Plan.find(params[:id])
  end
=end

end

app/views/plans/_payments.html.haml
%br
%br
%br
.container
  .row
    .col-xs-6.col-sm-6.col-md-3.col-lg-3
      .panel.price.panel-red
        .panel-heading.text-center
          %h1
            =@plan1.name
        .panel-body.text-center
          %h3
            $
            =@plan1.price
            %span
              Month
        %ul{class:"list-group list-group-flush text-center"}
          %h4
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Personal Use
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Unlimited Posts
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Free ads
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Free Offers
              %br/
        .panel-footer
          = link_to new_registration_path(plan_id: @plan1.id), class: "ruby" do
            %button.btn{class: "btn btn-lg btn-block btn-danger"} Register

    .col-xs-6.col-sm-6.col-md-3.col-lg-3
      .panel.price.panel-blue
        .panel-heading.text-center
          %h1
            =@plan2.name
        .panel-body.text-center
          %h3
            $
            =@plan2.price
            %span
              Month
        %ul{class:"list-group list-group-flush text-center"}
          %h4
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-info"}
              Personal Use
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-info"}
              Unlimited Posts
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-info"}
              Free ads
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-info"}
              Free Offers
              %br/
        .panel-footer
          = link_to new_registration_path(plan_id: @plan2.id), class: "ruby" do
            %button.btn{class: "btn btn-lg btn-block btn-info"} Register

    .col-xs-6.col-sm-6.col-md-3.col-lg-3
      .panel.price.panel-green
        .panel-heading.text-center
          %h1
            =@plan3.name
        .panel-body.text-center
          %h3
            $
            =@plan3.price
            %span
              Month
        %ul{class:"list-group list-group-flush text-center"}
          %h4
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-success"}
              Personal Use
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-success"}
              Unlimited Posts
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-success"}
              Free ads
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-success"}
              Free Offers
              %br/
        .panel-footer
          = link_to new_registration_path(plan_id: @plan3.id), class: "ruby" do
            %button.btn{class: "btn btn-lg btn-block btn-success"} Register

    .col-xs-6.col-sm-6.col-md-3.col-lg-3
      .panel.price.panel-grey
        .panel-heading.text-center
          %h1
            =@plan4.name
        .panel-body.text-center
          %h3
            $
            =@plan4.price
            %span
              Month
        %ul{class:"list-group list-group-flush text-center"}
          %h4
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Personal Use
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Unlimited Posts
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Free ads
              %br/
            %li{class:"list-group-item"}
              %i{class:"icon-ok text-danger"}
              Free Offers
              %br/
        .panel-footer
          = link_to new_registration_path(plan_id: @plan4.id), class: "ruby" do
            %button.btn{class: "btn btn-lg btn-block btn-info grey-button"} Register

app/views/plans/payments.html.erb
<%= render partial: 'payments' %>